name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download model AI
        run: |
          mkdir -p app/src/main/assets
          curl -L -o model.zip https://qaihub-public-assets.s3.us-west-2.amazonaws.com/qai-hub-models/models/real_esrgan_x4plus/releases/v0.55.0/real_esrgan_x4plus-tflite-float.zip
          unzip -o model.zip -d model_extracted
          find model_extracted -name "*.tflite" -exec cp {} app/src/main/assets/realesrgan_x4.tflite \;

      - name: Build APK Debug
        run: gradle assembleDebug

      - name: Upload hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: SuperUpscaler-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
